// lib/features/ui/widgets/mx_data.dart

/// Lista completa de estados de México (nombres oficiales).
const List<String> kEstadosOrden = [
  'Aguascalientes',
  'Baja California',
  'Baja California Sur',
  'Campeche',
  'Chiapas',
  'Chihuahua',
  'Ciudad de México',
  'Coahuila de Zaragoza',
  'Colima',
  'Durango',
  'Estado de México',
  'Guanajuato',
  'Guerrero',
  'Hidalgo',
  'Jalisco',
  'Michoacán de Ocampo',
  'Morelos',
  'Nayarit',
  'Nuevo León',
  'Oaxaca',
  'Puebla',
  'Querétaro',
  'Quintana Roo',
  'San Luis Potosí',
  'Sinaloa',
  'Sonora',
  'Tabasco',
  'Tamaulipas',
  'Tlaxcala',
  'Veracruz de Ignacio de la Llave',
  'Yucatán',
  'Zacatecas',
];

/// Estado -> Municipios/ciudades principales (subset amplio para Autocomplete).
final Map<String, List<String>> kMxMunicipios = {
  'Aguascalientes': [
    'Aguascalientes',
    'Jesús María',
    'San Francisco de los Romo',
    'Calvillo',
    'Rincón de Romos',
    'Pabellón de Arteaga',
    'Asientos',
    'Cosío',
    'El Llano',
    'San José de Gracia',
    'Tepezalá',
  ],
  'Baja California': [
    'Mexicali',
    'Tijuana',
    'Ensenada',
    'Tecate',
    'Playas de Rosarito',
    'San Felipe',
    'San Quintín',
  ],
  'Baja California Sur': ['La Paz', 'Los Cabos', 'Comondú', 'Loreto', 'Mulegé'],
  'Campeche': [
    'San Francisco de Campeche',
    'Carmen',
    'Champotón',
    'Escárcega',
    'Candelaria',
    'Hecelchakán',
    'Hopelchén',
    'Tenabo',
    'Calakmul',
    'Palizada',
    'Dzitbalché',
  ],
  'Chiapas': [
    'Tuxtla Gutiérrez',
    'San Cristóbal de las Casas',
    'Tapachula',
    'Comitán de Domínguez',
    'Palenque',
    'Tonalá',
    'Chiapa de Corzo',
    'Villaflores',
    'Ocosingo',
    'Arriaga',
    'Huixtla',
  ],
  'Chihuahua': [
    'Chihuahua',
    'Juárez',
    'Delicias',
    'Cuauhtémoc',
    'Parral',
    'Nuevo Casas Grandes',
    'Camargo',
    'Jiménez',
    'Meoqui',
    'Ahumada',
  ],
  'Ciudad de México': [
    // Alcaldías
    'Álvaro Obregón',
    'Azcapotzalco',
    'Benito Juárez',
    'Coyoacán',
    'Cuajimalpa de Morelos',
    'Cuauhtémoc',
    'Gustavo A. Madero',
    'Iztacalco',
    'Iztapalapa',
    'La Magdalena Contreras',
    'Miguel Hidalgo',
    'Milpa Alta',
    'Tláhuac',
    'Tlalpan',
    'Venustiano Carranza',
    'Xochimilco',
  ],
  'Coahuila de Zaragoza': [
    'Saltillo',
    'Torreón',
    'Monclova',
    'Piedras Negras',
    'Acuña',
    'Ramos Arizpe',
    'Frontera',
    'San Pedro',
    'Matamoros',
    'Nava',
    'San Juan de Sabinas',
  ],
  'Colima': [
    'Colima',
    'Manzanillo',
    'Tecomán',
    'Villa de Álvarez',
    'Comala',
    'Cuauhtémoc',
    'Armería',
    'Coquimatlán',
    'Ixtlahuacán',
    'Minatitlán',
  ],
  'Durango': [
    'Victoria de Durango',
    'Gómez Palacio',
    'Lerdo',
    'Canatlán',
    'Poanas',
    'Santiago Papasquiaro',
    'Cuencamé',
    'Pánuco de Coronado',
    'Pueblo Nuevo',
    'Mapimí',
  ],
  'Estado de México': [
    'Toluca',
    'Ecatepec de Morelos',
    'Naucalpan de Juárez',
    'Nezahualcóyotl',
    'Tlalnepantla de Baz',
    'Metepec',
    'Atizapán de Zaragoza',
    'Cuautitlán Izcalli',
    'Coacalco de Berriozábal',
    'Texcoco',
    'Chimalhuacán',
    'Cuautitlán',
    'Huixquilucan',
    'Valle de Chalco Solidaridad',
    'Tultitlán',
  ],
  'Guanajuato': [
    'León',
    'Irapuato',
    'Celaya',
    'Guanajuato',
    'Salamanca',
    'Silao de la Victoria',
    'San Miguel de Allende',
    'Dolores Hidalgo',
    'Valle de Santiago',
    'San Francisco del Rincón',
  ],
  'Guerrero': [
    'Chilpancingo de los Bravo',
    'Acapulco de Juárez',
    'Iguala de la Independencia',
    'Zihuatanejo de Azueta',
    'Taxco de Alarcón',
    'Chilapa de Álvarez',
    'Coyuca de Benítez',
    'Ometepec',
  ],
  'Hidalgo': [
    'Pachuca de Soto',
    'Tulancingo de Bravo',
    'Tizayuca',
    'Tula de Allende',
    'Ixmiquilpan',
    'Apan',
    'Actopan',
    'Huejutla de Reyes',
  ],
  'Jalisco': [
    'Guadalajara',
    'Zapopan',
    'San Pedro Tlaquepaque',
    'Tonalá',
    'Tlajomulco de Zúñiga',
    'Puerto Vallarta',
    'Tepatitlán de Morelos',
    'Lagos de Moreno',
    'Zapotlán el Grande',
  ],
  'Michoacán de Ocampo': [
    'Morelia',
    'Uruapan',
    'Zamora',
    'La Piedad',
    'Apatzingán',
    'Pátzcuaro',
    'Zitácuaro',
    'Lázaro Cárdenas',
  ],
  'Morelos': [
    'Cuernavaca',
    'Cuautla',
    'Jiutepec',
    'Temixco',
    'Yautepec',
    'Zacatepec',
    'Jojutla',
    'Emiliano Zapata',
  ],
  'Nayarit': [
    'Tepic',
    'Bahía de Banderas',
    'Santiago Ixcuintla',
    'Compostela',
    'Tuxpan',
    'Ixtlán del Río',
    'Xalisco',
  ],
  'Nuevo León': [
    'Monterrey',
    'Guadalupe',
    'San Nicolás de los Garza',
    'San Pedro Garza García',
    'Apodaca',
    'Santa Catarina',
    'General Escobedo',
    'Juárez',
    'García',
  ],
  'Oaxaca': [
    'Oaxaca de Juárez',
    'San Juan Bautista Tuxtepec',
    'Salina Cruz',
    'Juchitán de Zaragoza',
    'Huajuapan de León',
    'Tehuantepec',
    'Puerto Escondido',
  ],
  'Puebla': [
    'Puebla',
    'Tehuacán',
    'Atlixco',
    'San Martín Texmelucan',
    'Cholula',
    'Teziutlán',
    'Huauchinango',
  ],
  'Querétaro': [
    'Santiago de Querétaro',
    'Corregidora',
    'El Marqués',
    'San Juan del Río',
    'Tequisquiapan',
    'Pedro Escobedo',
    'Colón',
  ],
  'Quintana Roo': [
    'Chetumal (Othón P. Blanco)',
    'Benito Juárez (Cancún)',
    'Solidaridad (Playa del Carmen)',
    'Cozumel',
    'Tulum',
    'Isla Mujeres',
    'Felipe Carrillo Puerto',
    'Lázaro Cárdenas',
  ],
  'San Luis Potosí': [
    'San Luis Potosí',
    'Soledad de Graciano Sánchez',
    'Ciudad Valles',
    'Matehuala',
    'Rioverde',
    'Tamazunchale',
  ],
  'Sinaloa': [
    'Culiacán',
    'Mazatlán',
    'Ahome (Los Mochis)',
    'Guasave',
    'Navolato',
    'Salvador Alvarado (Guamúchil)',
  ],
  'Sonora': [
    'Hermosillo',
    'Cajeme (Ciudad Obregón)',
    'Nogales',
    'San Luis Río Colorado',
    'Navojoa',
    'Guaymas',
    'Agua Prieta',
  ],
  'Tabasco': [
    'Centro (Villahermosa)',
    'Cárdenas',
    'Comalcalco',
    'Macuspana',
    'Tenosique',
    'Paraíso',
    'Huimanguillo',
  ],
  'Tamaulipas': [
    'Ciudad Victoria',
    'Reynosa',
    'Matamoros',
    'Tampico',
    'Nuevo Laredo',
    'Altamira',
    'Madero',
    'Río Bravo',
  ],
  'Tlaxcala': [
    'Tlaxcala de Xicohténcatl',
    'Apizaco',
    'Huamantla',
    'Chiautempan',
    'Zacatelco',
    'San Pablo del Monte',
  ],
  'Veracruz de Ignacio de la Llave': [
    'Xalapa-Enríquez',
    'Veracruz',
    'Boca del Río',
    'Coatzacoalcos',
    'Poza Rica de Hidalgo',
    'Córdoba',
    'Orizaba',
    'Minatitlán',
    'Tuxpan',
  ],
  'Yucatán': [
    'Mérida',
    'Kanasín',
    'Valladolid',
    'Tizimín',
    'Progreso',
    'Umán',
    'Ticul',
    'Motul',
  ],
  'Zacatecas': [
    'Zacatecas',
    'Guadalupe',
    'Fresnillo',
    'Jerez de García Salinas',
    'Jalpa',
    'Sombrerete',
  ],
};
